#!/bin/sh
set -eu

: "${TUTTI_APP_PACKAGE_DIR:?}"
: "${TUTTI_APP_ID:?}"
: "${TUTTI_WORKSPACE_ID:?}"
: "${TUTTI_WORKSPACE_NAME:?}"
: "${TUTTI_APP_HOST:?}"
: "${TUTTI_APP_RUNTIME_DIR:?}"
: "${TUTTI_APP_DATA_DIR:?}"
: "${TUTTI_APP_LOG_DIR:?}"
: "${TUTTI_APP_PORT:?}"
: "${TUTTI_APP_BASE_URL:?}"
: "${TUTTI_APP_NODE:?}"

export TUTTI_APP_PACKAGE_DIR TUTTI_APP_ID TUTTI_WORKSPACE_ID TUTTI_WORKSPACE_NAME
export TUTTI_APP_HOST TUTTI_APP_RUNTIME_DIR TUTTI_APP_DATA_DIR TUTTI_APP_LOG_DIR
export TUTTI_APP_PORT TUTTI_APP_BASE_URL TUTTI_APP_NODE

mkdir -p "$TUTTI_APP_DATA_DIR" "$TUTTI_APP_LOG_DIR" "$TUTTI_APP_RUNTIME_DIR"
cd "$TUTTI_APP_PACKAGE_DIR"

exec "$TUTTI_APP_NODE" "$TUTTI_APP_PACKAGE_DIR/server/dist/main.js"
